# encoding: utf-8
require 'pry'

legal_markdown = <<EOF
graph TD
publisherRights{"Do you have the right to make this data open?"}
publisherRights --> |"yes, you have the rights to open this data up"| publisherOrigin{"Was the data originally created or generated by you?"}


publisherRights{"Do you have the right to make this data open?"} --> |"no, you don’t have the rights to open up this data"| copyrightURL["Where have you published the rights statement for this dataset?"]

publisherRights{"Do you have the right to make this data open?"}
publisherRights --> |"you’re not sure if you have the rights to publish this data as open data"| publisherOrigin{"Was the data originally created or generated by you?"}


publisherRights{"Do you have the right to make this data open?"}
publisherRights --> |"the rights in this data are complicated or unclear"| rightsRiskAssessment["Where do you detail the risks people might encounter if they use this data?"]
rightsRiskAssessment["Where do you detail the risks people might encounter if they use this data?"] --> copyrightURL["Where have you published the rights statement for this dataset?"]



copyrightURL["Where have you published the rights statement for this dataset?"] --> dataLicence["Under which licence can people reuse this data?"]

dataLicence{"Under which licence can people reuse this data?"} --> |"Creative Commons Attribution"| contentRights["Is there any copyright in the content of this data?"]

dataLicence{"Under which licence can people reuse this data?"} --> |"Creative Commons Attribution Share-Alike"| contentRights["Is there any copyright in the content of this data?"]

dataLicence{"Under which licence can people reuse this data?"} --> |"Creative Commons CCZero"| contentRights["Is there any copyright in the content of this data?"]

dataLicence{"Under which licence can people reuse this data?"} --> |"UK Open Government Licence"| contentRights["Is there any copyright in the content of this data?"]

dataLicence{"Under which licence can people reuse this data?"} --> |"Open Data Commons Attribution License"| contentRights["Is there any copyright in the content of this data?"]

dataLicence{"Under which licence can people reuse this data?"} --> |"Open Data Commons Open Database License (ODbL)"| contentRights["Is there any copyright in the content of this data?"]

dataLicence{"Under which licence can people reuse this data?"} --> |"Open Data Commons Public Domain Dedication and Licence (PDDL)"| contentRights["Is there any copyright in the content of this data?"]

dataLicence{"Under which licence can people reuse this data?"}
dataLicence --> |"Not applicable"| dataNotApplicable{"Why doesn't a licence apply to this data?"}


dataLicence{"Under which licence can people reuse this data?"}
dataLicence --> |"Other..."| otherDataLicenceName["What is the name of the licence?"]
otherDataLicenceName["What is the name of the licence?"] --> contentRights["Is there any copyright in the content of this data?"]



contentRights{"Is there any copyright in the content of this data?"}
contentRights --> |"no, the data only contains facts and numbers"| explicitWaiver{"Is the content of the data marked as public domain?"}


contentRights{"Is there any copyright in the content of this data?"}
contentRights --> |"yes, and the rights are all held by the same person or organisation"| contentLicence{"Under which licence can others reuse content?"}


contentRights{"Is there any copyright in the content of this data?"}
contentRights --> |"yes, and the rights are held by different people or organisations"| contentRightsURL["Where are the rights and licensing of the content explained?"]
contentRightsURL["Where are the rights and licensing of the content explained?"] --> dataPersonal["Can individuals be identified from this data?"]



dataPersonal{"Can individuals be identified from this data?"} --> |"no, the data is not about people or their activities"| finalSection["End"]

dataPersonal{"Can individuals be identified from this data?"}
dataPersonal --> |"no, the data has been anonymised by aggregating individuals into groups, so they can't be distinguished from other people in the group"| statisticalAnonAudited{"Has your anonymisation process been independently audited?"}


dataPersonal{"Can individuals be identified from this data?"}
dataPersonal --> |"yes, there is a risk that individuals be identified, for example by third parties with access to extra information"| appliedAnon{"Have you attempted to reduce or remove the possibility of individuals being identified?"}





appliedAnon{&quot;Have you attempted to reduce or remove the possibility of individuals being identified?&quot;}
appliedAnon --&gt; |&quot;false&quot;| lawfulDisclosure{&quot;Are you required or permitted by law to publish this data about individuals?&quot;}


lawfulDisclosure{&quot;Are you required or permitted by law to publish this data about individuals?&quot;} --&gt; |&quot;false&quot;| finalSection[&quot;End&quot;]

lawfulDisclosure{&quot;Are you required or permitted by law to publish this data about individuals?&quot;}
lawfulDisclosure --&gt; |&quot;true&quot;| lawfulDisclosureURL[&quot;Where do you document your right to publish data about individuals?&quot;]
lawfulDisclosureURL[&quot;Where do you document your right to publish data about individuals?&quot;] --&gt; finalSection[&quot;End&quot;]


appliedAnon{&quot;Have you attempted to reduce or remove the possibility of individuals being identified?&quot;}
appliedAnon --&gt; |&quot;true&quot;| privacyImpactAssessmentExists{&quot;Have you carried out a Privacy Impact Assessment?&quot;}


privacyImpactAssessmentExists{&quot;Have you carried out a Privacy Impact Assessment?&quot;} --&gt; |&quot;false&quot;| finalSection[&quot;End&quot;]

privacyImpactAssessmentExists{&quot;Have you carried out a Privacy Impact Assessment?&quot;}
privacyImpactAssessmentExists --&gt; |&quot;true&quot;| privacyImpactAssessmentUrl[&quot;Where is your Privacy Impact Assessment published?&quot;]
privacyImpactAssessmentUrl[&quot;Where is your Privacy Impact Assessment published?&quot;] --&gt; finalSection[&quot;End&quot;]


statisticalAnonAudited{&quot;Has your anonymisation process been independently audited?&quot;} --&gt; |&quot;false&quot;| finalSection[&quot;End&quot;]

statisticalAnonAudited{&quot;Has your anonymisation process been independently audited?&quot;} --&gt; |&quot;true&quot;| finalSection[&quot;End&quot;]

contentLicence{&quot;Under which licence can others reuse content?&quot;}
contentLicence --&gt; |&quot;Other...&quot;| otherContentLicenceName[&quot;What&#x27;s the name of the licence?&quot;]
otherContentLicenceName[&quot;What&#x27;s the name of the licence?&quot;] --&gt; dataPersonal[&quot;Can individuals be identified from this data?&quot;]


contentLicence{&quot;Under which licence can others reuse content?&quot;}
contentLicence --&gt; |&quot;Not applicable&quot;| contentNotApplicable{&quot;Why doesn&#x27;t a licence apply to the content of the data?&quot;}


contentNotApplicable{&quot;Why doesn&#x27;t a licence apply to the content of the data?&quot;}
contentNotApplicable --&gt; |&quot;copyright has been waived&quot;| contentWaiver{&quot;Which waiver do you use to waive copyright?&quot;}


contentWaiver{&quot;Which waiver do you use to waive copyright?&quot;}
contentWaiver --&gt; |&quot;Other...&quot;| contentOtherWaiver[&quot;Where is the waiver for the copyright?&quot;]
contentOtherWaiver[&quot;Where is the waiver for the copyright?&quot;] --&gt; dataPersonal[&quot;Can individuals be identified from this data?&quot;]


contentWaiver{&quot;Which waiver do you use to waive copyright?&quot;} --&gt; |&quot;Creative Commons CCZero&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

contentNotApplicable{&quot;Why doesn&#x27;t a licence apply to the content of the data?&quot;} --&gt; |&quot;copyright has expired&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

contentNotApplicable{&quot;Why doesn&#x27;t a licence apply to the content of the data?&quot;} --&gt; |&quot;there is no copyright in the content of this data&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

contentLicence{&quot;Under which licence can others reuse content?&quot;} --&gt; |&quot;UK Open Government Licence&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

contentLicence{&quot;Under which licence can others reuse content?&quot;} --&gt; |&quot;Creative Commons CCZero&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

contentLicence{&quot;Under which licence can others reuse content?&quot;} --&gt; |&quot;Creative Commons Attribution Share-Alike&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

contentLicence{&quot;Under which licence can others reuse content?&quot;} --&gt; |&quot;Creative Commons Attribution&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

explicitWaiver{&quot;Is the content of the data marked as public domain?&quot;} --&gt; |&quot;false&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

explicitWaiver{&quot;Is the content of the data marked as public domain?&quot;} --&gt; |&quot;true&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

dataNotApplicable{&quot;Why doesn&#x27;t a licence apply to this data?&quot;}
dataNotApplicable --&gt; |&quot;copyright and database rights have been waived&quot;| dataWaiver{&quot;Which waiver do you use to waive rights in the data?&quot;}


dataWaiver{&quot;Which waiver do you use to waive rights in the data?&quot;}
dataWaiver --&gt; |&quot;Other...&quot;| dataOtherWaiver[&quot;Where is the waiver for the rights in the data?&quot;]
dataOtherWaiver[&quot;Where is the waiver for the rights in the data?&quot;] --&gt; contentRights[&quot;Is there any copyright in the content of this data?&quot;]


dataWaiver{&quot;Which waiver do you use to waive rights in the data?&quot;} --&gt; |&quot;Creative Commons CCZero&quot;| contentRights[&quot;Is there any copyright in the content of this data?&quot;]

dataWaiver{&quot;Which waiver do you use to waive rights in the data?&quot;} --&gt; |&quot;Open Data Commons Public Domain Dedication and Licence (PDDL)&quot;| contentRights[&quot;Is there any copyright in the content of this data?&quot;]

dataNotApplicable{&quot;Why doesn&#x27;t a licence apply to this data?&quot;} --&gt; |&quot;copyright and database rights have expired&quot;| contentRights[&quot;Is there any copyright in the content of this data?&quot;]

dataNotApplicable{&quot;Why doesn&#x27;t a licence apply to this data?&quot;} --&gt; |&quot;there are no copyright or database rights in this data&quot;| contentRights[&quot;Is there any copyright in the content of this data?&quot;]

publisherOrigin{&quot;Was the data originally created or generated by you?&quot;}
publisherOrigin --&gt; |&quot;no, it uses external sources&quot;| thirdPartyOrigin{&quot;Was some of this data extracted or calculated from other data?&quot;}


thirdPartyOrigin{&quot;Was some of this data extracted or calculated from other data?&quot;} --&gt; |&quot;false&quot;| copyrightURL[&quot;Where have you published the rights statement for this dataset?&quot;]

thirdPartyOrigin{&quot;Was some of this data extracted or calculated from other data?&quot;}
thirdPartyOrigin --&gt; |&quot;true&quot;| thirdPartyOpen{&quot;Are all sources of this data already published as open data?&quot;}


thirdPartyOpen{&quot;Are all sources of this data already published as open data?&quot;} --&gt; |&quot;false&quot;| copyrightURL[&quot;Where have you published the rights statement for this dataset?&quot;]

thirdPartyOpen{&quot;Are all sources of this data already published as open data?&quot;} --&gt; |&quot;true&quot;| copyrightURL[&quot;Where have you published the rights statement for this dataset?&quot;]

publisherOrigin{&quot;Was the data originally created or generated by you?&quot;} --&gt; |&quot;yes&quot;| copyrightURL[&quot;Where have you published the rights statement for this dataset?&quot;]

class copyrightURL,rightsRiskAssessment,sourceDocumentationUrl,lawfulDisclosure,privacyImpactAssessmentExists,individualConsentURL,dbStaffConsulted pilot;
class sourceDocumentationMetadata,explicitWaiver,statisticalAnonAudited,lawfulDisclosureURL,privacyImpactAssessmentUrl,piaAudited,anonymisationAudited standard;
EOF

practical_markdown = <<EOF
dataTitle["What's this data called?"] --> documentationUrl["Where is it described?"]

              documentationUrl["Where is it described?"] --> publisher["Who publishes this data?"]

              publisher["Who publishes this data?"] --> publisherUrl["What is the website of the publisher?"]

              publisherUrl["What is the website of the publisher?"] --> releaseType["What kind of release is this?"]

                  releaseType{"What kind of release is this?"}
              releaseType --> |"a one-off release of a single dataset"| timeSensitive{"Will your data go out of date?"}


              releaseType{"What kind of release is this?"}
              releaseType --> |"a one-off release of a set of related datasets"| timeSensitive{"Will your data go out of date?"}


              releaseType{"What kind of release is this?"}
              releaseType --> |"ongoing release of a series of related datasets"| frequentChanges{"Does this data change at least daily?"}


              releaseType{"What kind of release is this?"}
              releaseType --> |"a service or API for accessing open data"| serviceType{"Does the data behind your API change?"}



                  onWebsite{"Is there a link to your data from your main website?"}
              onWebsite --> |"true"| webpage["Which page on your website links to the data?"]
                webpage["Which page on your website links to the data?"] --> listed["Is your data listed within a collection?"]


              onWebsite{"Is there a link to your data from your main website?"} --> |"false"| listed["Is your data listed within a collection?"]


                  listed{"Is your data listed within a collection?"}
              listed --> |"true"| listing["Where is it listed?"]
                listing["Where is it listed?"] --> referenced["Is this data referenced from your own publications?"]


              listed{"Is your data listed within a collection?"} --> |"false"| referenced["Is this data referenced from your own publications?"]


                  referenced{"Is this data referenced from your own publications?"}
              referenced --> |"true"| reference["Where is your data referenced?"]
                reference["Where is your data referenced?"] --> qualityUrl["Where do you document issues with the quality of this data?"]


              referenced{"Is this data referenced from your own publications?"} --> |"false"| qualityUrl["Where do you document issues with the quality of this data?"]


              qualityUrl["Where do you document issues with the quality of this data?"] --> qualityControlUrl["Where is your quality control process described?"]

              qualityControlUrl["Where is your quality control process described?"] --> backups["Do you take offsite backups?"]

                  backups{"Do you take offsite backups?"} --> |"true"| onGoingAvailability["How long will this data be available for?"]

              backups{"Do you take offsite backups?"} --> |"false"| onGoingAvailability["How long will this data be available for?"]


                  onGoingAvailability{"How long will this data be available for?"} --> |"it might disappear at any time"| machineReadable["Is this data machine-readable?"]

              onGoingAvailability{"How long will this data be available for?"} --> |"it's available experimentally but should be around for another year or so"| machineReadable["Is this data machine-readable?"]

              onGoingAvailability{"How long will this data be available for?"} --> |"it's in your medium-term plans so should be around for a couple of years"| machineReadable["Is this data machine-readable?"]

              onGoingAvailability{"How long will this data be available for?"} --> |"it's part of your day-to-day operations so will stay published for a long time"| machineReadable["Is this data machine-readable?"]


                  machineReadable{"Is this data machine-readable?"} --> |"true"| openStandard["Is this data in a standard open format?"]

              machineReadable{"Is this data machine-readable?"} --> |"false"| openStandard["Is this data in a standard open format?"]


                  openStandard{"Is this data in a standard open format?"} --> |"true"| dataType["What kind of data is being provided as part of this dataset?"]

              openStandard{"Is this data in a standard open format?"} --> |"false"| dataType["What kind of data is being provided as part of this dataset?"]


                  dataType{"What kind of data is being provided as part of this dataset?"} --> |"human-readable documents"| identifiers["Does your data use persistent identifiers?"]

              dataType{"What kind of data is being provided as part of this dataset?"} --> |"statistical data like counts, averages and percentages"| identifiers["Does your data use persistent identifiers?"]

              dataType{"What kind of data is being provided as part of this dataset?"} --> |"geographic information, such as points and boundaries"| identifiers["Does your data use persistent identifiers?"]

              dataType{"What kind of data is being provided as part of this dataset?"} --> |"other kinds of structured data"| identifiers["Does your data use persistent identifiers?"]


                  identifiers{"Does your data use persistent identifiers?"}
              identifiers --> |"true"| resolvingIds{"Can the identifiers in your data be used to find extra information?"}


              identifiers{"Does your data use persistent identifiers?"} --> |"false"| provenance["Do you provide machine-readable provenance for your data?"]


                  provenance{"Do you provide machine-readable provenance for your data?"} --> |"true"| digitalCertificate["Where do you describe how people can verify that data they receive comes from you?"]

              provenance{"Do you provide machine-readable provenance for your data?"} --> |"false"| digitalCertificate["Where do you describe how people can verify that data they receive comes from you?"]


              digitalCertificate["Where do you describe how people can verify that data they receive comes from you?"] --> technicalDocumentation["Where is the technical documentation for the data?"]

              technicalDocumentation["Where is the technical documentation for the data?"] --> vocabulary["Do the data formats use vocabularies or schemas?"]

                  vocabulary{"Do the data formats use vocabularies or schemas?"}
              vocabulary --> |"true"| schemaDocumentationUrl["Where is documentation about your data vocabularies?"]
                schemaDocumentationUrl["Where is documentation about your data vocabularies?"] --> codelists["Are there any codes used in this data?"]


              vocabulary{"Do the data formats use vocabularies or schemas?"} --> |"false"| codelists["Are there any codes used in this data?"]


                  codelists{"Are there any codes used in this data?"}
              codelists --> |"true"| codelistDocumentationUrl["Where are any codes in your data documented?"]
                codelistDocumentationUrl["Where are any codes in your data documented?"] --> contactUrl["Where can people find out how to contact someone with questions about this data?"]


              codelists{"Are there any codes used in this data?"} --> |"false"| contactUrl["Where can people find out how to contact someone with questions about this data?"]


              contactUrl["Where can people find out how to contact someone with questions about this data?"] --> improvementsContact["Where can people find out how to improve the way your data is published?"]

              improvementsContact["Where can people find out how to improve the way your data is published?"] --> dataProtectionUrl["Where can people find out how to contact someone with questions about privacy?"]

              dataProtectionUrl["Where can people find out how to contact someone with questions about privacy?"] --> socialMedia["Do you use social media to connect with people who use your data?"]

                  socialMedia{"Do you use social media to connect with people who use your data?"}
              socialMedia --> |"true"| account["Which social media accounts can people reach you on?"]
                account["Which social media accounts can people reach you on?"] --> forum["Where should people discuss this dataset?"]


              socialMedia{"Do you use social media to connect with people who use your data?"} --> |"false"| forum["Where should people discuss this dataset?"]


              forum["Where should people discuss this dataset?"] --> engagementTeam["Do you have anyone who actively builds a community around this data?"]

                  engagementTeam{"Do you have anyone who actively builds a community around this data?"}
              engagementTeam --> |"true"| engagementTeamUrl["Where is their home page?"]
                engagementTeamUrl["Where is their home page?"] --> libraries["Where do you list tools to work with your data?"]


              engagementTeam{"Do you have anyone who actively builds a community around this data?"} --> |"false"| libraries["Where do you list tools to work with your data?"]





            resolvingIds{&quot;Can the identifiers in your data be used to find extra information?&quot;} --&gt; |&quot;yes, the identifiers are URLs that resolve to give information&quot;| provenance[&quot;Do you provide machine-readable provenance for your data?&quot;]

          resolvingIds{&quot;Can the identifiers in your data be used to find extra information?&quot;}
              resolvingIds --&gt; |&quot;yes, there is a service that people can use to resolve the identifiers&quot;| resolutionServiceURL[&quot;Where is the service that is used to resolve the identifiers?&quot;]
                resolutionServiceURL[&quot;Where is the service that is used to resolve the identifiers?&quot;] --&gt; provenance[&quot;Do you provide machine-readable provenance for your data?&quot;]


          resolvingIds{&quot;Can the identifiers in your data be used to find extra information?&quot;} --&gt; |&quot;no, the identifiers can&#x27;t be used to find extra information&quot;| provenance[&quot;Do you provide machine-readable provenance for your data?&quot;]

          serviceType{&quot;Does the data behind your API change?&quot;}
              serviceType --&gt; |&quot;yes, the API gives access to changing data&quot;| dumpFrequency{&quot;How frequently do you create a new database dump?&quot;}


          dumpFrequency{&quot;How frequently do you create a new database dump?&quot;} --&gt; |&quot;within a day of any change&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          dumpFrequency{&quot;How frequently do you create a new database dump?&quot;} --&gt; |&quot;within a week of any change&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          dumpFrequency{&quot;How frequently do you create a new database dump?&quot;} --&gt; |&quot;at least every month&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          dumpFrequency{&quot;How frequently do you create a new database dump?&quot;} --&gt; |&quot;less frequently than once a month&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          serviceType{&quot;Does the data behind your API change?&quot;}
              serviceType --&gt; |&quot;no, the API gives access to unchanging data&quot;| timeSensitive{&quot;Will your data go out of date?&quot;}


          timeSensitive{&quot;Will your data go out of date?&quot;} --&gt; |&quot;no, this data does not contain any time-sensitive information&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          timeSensitive{&quot;Will your data go out of date?&quot;} --&gt; |&quot;yes, this data will go out of date over time but it&#x27;s time stamped&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          timeSensitive{&quot;Will your data go out of date?&quot;} --&gt; |&quot;yes, this data will go out of date&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          frequentChanges{&quot;Does this data change at least daily?&quot;} --&gt; |&quot;false&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          frequentChanges{&quot;Does this data change at least daily?&quot;}
              frequentChanges --&gt; |&quot;true&quot;| seriesType{&quot;What type of dataset series is this?&quot;}


          seriesType{&quot;What type of dataset series is this?&quot;} --&gt; |&quot;regular aggregates of changing data&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          seriesType{&quot;What type of dataset series is this?&quot;}
              seriesType --&gt; |&quot;regular copies of a complete database&quot;| changeFeed{&quot;Is a feed of changes available?&quot;}


          changeFeed{&quot;Is a feed of changes available?&quot;} --&gt; |&quot;false&quot;| onWebsite[&quot;Is there a link to your data from your main website?&quot;]

          changeFeed{&quot;Is a feed of changes available?&quot;}
              changeFeed --&gt; |&quot;true&quot;| changeFeedUrl[&quot;Where is your feed of changes?&quot;]
                changeFeedUrl[&quot;Where is your feed of changes?&quot;] --&gt; onWebsite[&quot;Is there a link to your data from your main website?&quot;]


              class onWebsite,listed,referenced,qualityUrl,backups,openStandard,identifiers,socialMedia,forum,provideDumps,corrected,slaUrl,resolutionServiceURL,schemaDocumentationUrl,codelistDocumentationUrl,correctionReporting,correctionDiscovery standard;
              class qualityControlUrl,provenance,digitalCertificate,engagementTeam,libraries,changeFeed,statusUrl,externalUrls exemplar;
              class machineReadable,technicalDocumentation,contactUrl,improvementsContact,dataProtectionUrl pilot;
EOF

When(/^I navigate to "(.*?)"$/) do |url|
  visit "#{url}"
  # visit path_to(url)
end

When(/^I select "(.*?)" from the "(.*?)" dropdown$/) do |text, field|
  # find_field('questionairre_selection').find(field)
  # select text, from: field
  page.select text, :from => field
end

# When(/^I select "(.*?)"/) do |text|
#   # page.select text, from: field
#   page.select(text, :from => page)
# end

# above can cover both practical and jurisdiction

When(/^I press "(.*?)"$/) do |name|
  click_button name
end

Then(/^the page should contain legal markdown$/) do
  save_and_open_page
  assert_true page.body.gsub(/\s+/, "").include? (legal_markdown.gsub(/\s+/, ""))
end

Then(/^the page should contain practical markdown$/) do
  save_and_open_page
  assert_true page.body.gsub(/\s+/, "").include? (practical_markdown.gsub(/\s+/, ""))
end
