# encoding: utf-8
require 'pry'

legal_markdown = <<EOF
  graph TD
  publisherRights{"Do you have the right to make this data open?"}
  publisherRights --> |"yes, you have the rights to open this data up"| publisherOrigin{"Was the data originally created or generated by you?"}


  publisherRights{"Do you have the right to make this data open?"} --> |"no, you don’t have the rights to open up this data"| copyrightURL["Where have you published the rights statement for this dataset?"]

  publisherRights{"Do you have the right to make this data open?"}
  publisherRights --> |"you’re not sure if you have the rights to publish this data as open data"| publisherOrigin{"Was the data originally created or generated by you?"}


  publisherRights{"Do you have the right to make this data open?"}
  publisherRights --> |"the rights in this data are complicated or unclear"| rightsRiskAssessment["Where do you detail the risks people might encounter if they use this data?"]
  rightsRiskAssessment["Where do you detail the risks people might encounter if they use this data?"] --> copyrightURL["Where have you published the rights statement for this dataset?"]



  copyrightURL["Where have you published the rights statement for this dataset?"] --> dataLicence["Under which licence can people reuse this data?"]

  dataLicence{"Under which licence can people reuse this data?"} --> |"Creative Commons Attribution"| contentRights["Is there any copyright in the content of this data?"]

  dataLicence{"Under which licence can people reuse this data?"} --> |"Creative Commons Attribution Share-Alike"| contentRights["Is there any copyright in the content of this data?"]

  dataLicence{"Under which licence can people reuse this data?"} --> |"Creative Commons CCZero"| contentRights["Is there any copyright in the content of this data?"]

  dataLicence{"Under which licence can people reuse this data?"} --> |"UK Open Government Licence"| contentRights["Is there any copyright in the content of this data?"]

  dataLicence{"Under which licence can people reuse this data?"} --> |"Open Data Commons Attribution License"| contentRights["Is there any copyright in the content of this data?"]

  dataLicence{"Under which licence can people reuse this data?"} --> |"Open Data Commons Open Database License (ODbL)"| contentRights["Is there any copyright in the content of this data?"]

  dataLicence{"Under which licence can people reuse this data?"} --> |"Open Data Commons Public Domain Dedication and Licence (PDDL)"| contentRights["Is there any copyright in the content of this data?"]

  dataLicence{"Under which licence can people reuse this data?"}
  dataLicence --> |"Not applicable"| dataNotApplicable{"Why doesn't a licence apply to this data?"}


  dataLicence{"Under which licence can people reuse this data?"}
  dataLicence --> |"Other..."| otherDataLicenceName["What is the name of the licence?"]
  otherDataLicenceName["What is the name of the licence?"] --> contentRights["Is there any copyright in the content of this data?"]



  contentRights{"Is there any copyright in the content of this data?"}
  contentRights --> |"no, the data only contains facts and numbers"| explicitWaiver{"Is the content of the data marked as public domain?"}


  contentRights{"Is there any copyright in the content of this data?"}
  contentRights --> |"yes, and the rights are all held by the same person or organisation"| contentLicence{"Under which licence can others reuse content?"}


  contentRights{"Is there any copyright in the content of this data?"}
  contentRights --> |"yes, and the rights are held by different people or organisations"| contentRightsURL["Where are the rights and licensing of the content explained?"]
  contentRightsURL["Where are the rights and licensing of the content explained?"] --> dataPersonal["Can individuals be identified from this data?"]



  dataPersonal{"Can individuals be identified from this data?"} --> |"no, the data is not about people or their activities"| finalSection["End"]

  dataPersonal{"Can individuals be identified from this data?"}
  dataPersonal --> |"no, the data has been anonymised by aggregating individuals into groups, so they can't be distinguished from other people in the group"| statisticalAnonAudited{"Has your anonymisation process been independently audited?"}


  dataPersonal{"Can individuals be identified from this data?"}
  dataPersonal --> |"yes, there is a risk that individuals be identified, for example by third parties with access to extra information"| appliedAnon{"Have you attempted to reduce or remove the possibility of individuals being identified?"}





  appliedAnon{&quot;Have you attempted to reduce or remove the possibility of individuals being identified?&quot;}
  appliedAnon --&gt; |&quot;false&quot;| lawfulDisclosure{&quot;Are you required or permitted by law to publish this data about individuals?&quot;}


  lawfulDisclosure{&quot;Are you required or permitted by law to publish this data about individuals?&quot;} --&gt; |&quot;false&quot;| finalSection[&quot;End&quot;]

  lawfulDisclosure{&quot;Are you required or permitted by law to publish this data about individuals?&quot;}
  lawfulDisclosure --&gt; |&quot;true&quot;| lawfulDisclosureURL[&quot;Where do you document your right to publish data about individuals?&quot;]
  lawfulDisclosureURL[&quot;Where do you document your right to publish data about individuals?&quot;] --&gt; finalSection[&quot;End&quot;]


  appliedAnon{&quot;Have you attempted to reduce or remove the possibility of individuals being identified?&quot;}
  appliedAnon --&gt; |&quot;true&quot;| privacyImpactAssessmentExists{&quot;Have you carried out a Privacy Impact Assessment?&quot;}


  privacyImpactAssessmentExists{&quot;Have you carried out a Privacy Impact Assessment?&quot;} --&gt; |&quot;false&quot;| finalSection[&quot;End&quot;]

  privacyImpactAssessmentExists{&quot;Have you carried out a Privacy Impact Assessment?&quot;}
  privacyImpactAssessmentExists --&gt; |&quot;true&quot;| privacyImpactAssessmentUrl[&quot;Where is your Privacy Impact Assessment published?&quot;]
  privacyImpactAssessmentUrl[&quot;Where is your Privacy Impact Assessment published?&quot;] --&gt; finalSection[&quot;End&quot;]


  statisticalAnonAudited{&quot;Has your anonymisation process been independently audited?&quot;} --&gt; |&quot;false&quot;| finalSection[&quot;End&quot;]

  statisticalAnonAudited{&quot;Has your anonymisation process been independently audited?&quot;} --&gt; |&quot;true&quot;| finalSection[&quot;End&quot;]

  contentLicence{&quot;Under which licence can others reuse content?&quot;}
  contentLicence --&gt; |&quot;Other...&quot;| otherContentLicenceName[&quot;What&#x27;s the name of the licence?&quot;]
  otherContentLicenceName[&quot;What&#x27;s the name of the licence?&quot;] --&gt; dataPersonal[&quot;Can individuals be identified from this data?&quot;]


  contentLicence{&quot;Under which licence can others reuse content?&quot;}
  contentLicence --&gt; |&quot;Not applicable&quot;| contentNotApplicable{&quot;Why doesn&#x27;t a licence apply to the content of the data?&quot;}


  contentNotApplicable{&quot;Why doesn&#x27;t a licence apply to the content of the data?&quot;}
  contentNotApplicable --&gt; |&quot;copyright has been waived&quot;| contentWaiver{&quot;Which waiver do you use to waive copyright?&quot;}


  contentWaiver{&quot;Which waiver do you use to waive copyright?&quot;}
  contentWaiver --&gt; |&quot;Other...&quot;| contentOtherWaiver[&quot;Where is the waiver for the copyright?&quot;]
  contentOtherWaiver[&quot;Where is the waiver for the copyright?&quot;] --&gt; dataPersonal[&quot;Can individuals be identified from this data?&quot;]


  contentWaiver{&quot;Which waiver do you use to waive copyright?&quot;} --&gt; |&quot;Creative Commons CCZero&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  contentNotApplicable{&quot;Why doesn&#x27;t a licence apply to the content of the data?&quot;} --&gt; |&quot;copyright has expired&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  contentNotApplicable{&quot;Why doesn&#x27;t a licence apply to the content of the data?&quot;} --&gt; |&quot;there is no copyright in the content of this data&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  contentLicence{&quot;Under which licence can others reuse content?&quot;} --&gt; |&quot;UK Open Government Licence&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  contentLicence{&quot;Under which licence can others reuse content?&quot;} --&gt; |&quot;Creative Commons CCZero&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  contentLicence{&quot;Under which licence can others reuse content?&quot;} --&gt; |&quot;Creative Commons Attribution Share-Alike&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  contentLicence{&quot;Under which licence can others reuse content?&quot;} --&gt; |&quot;Creative Commons Attribution&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  explicitWaiver{&quot;Is the content of the data marked as public domain?&quot;} --&gt; |&quot;false&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  explicitWaiver{&quot;Is the content of the data marked as public domain?&quot;} --&gt; |&quot;true&quot;| dataPersonal[&quot;Can individuals be identified from this data?&quot;]

  dataNotApplicable{&quot;Why doesn&#x27;t a licence apply to this data?&quot;}
  dataNotApplicable --&gt; |&quot;copyright and database rights have been waived&quot;| dataWaiver{&quot;Which waiver do you use to waive rights in the data?&quot;}


  dataWaiver{&quot;Which waiver do you use to waive rights in the data?&quot;}
  dataWaiver --&gt; |&quot;Other...&quot;| dataOtherWaiver[&quot;Where is the waiver for the rights in the data?&quot;]
  dataOtherWaiver[&quot;Where is the waiver for the rights in the data?&quot;] --&gt; contentRights[&quot;Is there any copyright in the content of this data?&quot;]


  dataWaiver{&quot;Which waiver do you use to waive rights in the data?&quot;} --&gt; |&quot;Creative Commons CCZero&quot;| contentRights[&quot;Is there any copyright in the content of this data?&quot;]

  dataWaiver{&quot;Which waiver do you use to waive rights in the data?&quot;} --&gt; |&quot;Open Data Commons Public Domain Dedication and Licence (PDDL)&quot;| contentRights[&quot;Is there any copyright in the content of this data?&quot;]

  dataNotApplicable{&quot;Why doesn&#x27;t a licence apply to this data?&quot;} --&gt; |&quot;copyright and database rights have expired&quot;| contentRights[&quot;Is there any copyright in the content of this data?&quot;]

  dataNotApplicable{&quot;Why doesn&#x27;t a licence apply to this data?&quot;} --&gt; |&quot;there are no copyright or database rights in this data&quot;| contentRights[&quot;Is there any copyright in the content of this data?&quot;]

  publisherOrigin{&quot;Was the data originally created or generated by you?&quot;}
  publisherOrigin --&gt; |&quot;no, it uses external sources&quot;| thirdPartyOrigin{&quot;Was some of this data extracted or calculated from other data?&quot;}


  thirdPartyOrigin{&quot;Was some of this data extracted or calculated from other data?&quot;} --&gt; |&quot;false&quot;| copyrightURL[&quot;Where have you published the rights statement for this dataset?&quot;]

  thirdPartyOrigin{&quot;Was some of this data extracted or calculated from other data?&quot;}
  thirdPartyOrigin --&gt; |&quot;true&quot;| thirdPartyOpen{&quot;Are all sources of this data already published as open data?&quot;}


  thirdPartyOpen{&quot;Are all sources of this data already published as open data?&quot;} --&gt; |&quot;false&quot;| copyrightURL[&quot;Where have you published the rights statement for this dataset?&quot;]

  thirdPartyOpen{&quot;Are all sources of this data already published as open data?&quot;} --&gt; |&quot;true&quot;| copyrightURL[&quot;Where have you published the rights statement for this dataset?&quot;]

  publisherOrigin{&quot;Was the data originally created or generated by you?&quot;} --&gt; |&quot;yes&quot;| copyrightURL[&quot;Where have you published the rights statement for this dataset?&quot;]

  class copyrightURL,rightsRiskAssessment,sourceDocumentationUrl,lawfulDisclosure,privacyImpactAssessmentExists,individualConsentURL,dbStaffConsulted pilot;
  class sourceDocumentationMetadata,explicitWaiver,statisticalAnonAudited,lawfulDisclosureURL,privacyImpactAssessmentUrl,piaAudited,anonymisationAudited standard;
EOF

When(/^I navigate to "(.*?)"$/) do |url|
  visit "#{url}"
  # visit path_to(url)
end

When(/^I select "(.*?)" from the "(.*?)" dropdown$/) do |text, field|
  # find_field('questionairre_selection').find(field)
  # select text, from: field
  page.select text, :from => field
end

# When(/^I select "(.*?)"/) do |text|
#   # page.select text, from: field
#   page.select(text, :from => page)
# end

# above can cover both practical and jurisdiction

When(/^I press "(.*?)"$/) do |name|
  click_button name
end

Then(/^the page should contain "(.*?)"$/) do |text|
  page.body.should include(text)
end

Then(/^the page should contain legal markdown$/) do
  save_and_open_page
  assert_true page.has_content?(legal_markdown)
end
